#!/bin/bash

# Triggered when a kernel is removed. Version is given as an argument.
inst_kern="${1}"
ukisuffix="uki"

TARGET_EFI_ROOT_DIR="/boot/efi"
TARGET_UKI_ROOT_DIR="${TARGET_EFI_ROOT_DIR}/EFI"
TARGET_UKI_BOOT_DIR="${TARGET_UKI_ROOT_DIR}/Linux"

# If EFI Linux target dir does not exist, exit silently.
[ -d "${TARGET_UKI_BOOT_DIR}" ] || { exit 0; }

#
echo "Attempting to clean up UKI image for ${inst_kern}"

TARGET_UKI_FILE="${TARGET_UKI_BOOT_DIR}/vmlinuz-${inst_kern}-${ukisuffix}*.efi"

if [ -f "${TARGET_UKI_FILE}" ]; then
    echo "Matching Unified Kernel Image file detected at '${TARGET_UKI_FILE}'"
    echo "Proceeding with cleanup"
    rm -f "${TARGET_UKI_FILE}" || { echo "Could not remove ${TARGET_UKI_FILE}." ; }
    if [ $(command -v sbctl) ]; then
        echo "Attempting to clean up sbctl reference to target UKI file"
        $(command -v sbctl) remove-file "${TARGET_UKI_FILE}" || { echo "Error while cleaning up sbctl database."; exit 0; }
    fi
fi
