#!/bin/bash -e

#######################################################################
###                                                                 ###
### This is a regenerate_uki variant maintained by the PikaOS team. ###
###                                                                 ###
### The original regenerate_uki script was developed targeting Arch ###
### and distro-specific commands and tuning needed to be made.      ###
###                                                                 ###
### This regenerate_uki variant targets PikaOS 4 specifically.      ###
###                                                                 ###
### Here there be dragons. And cute birbs, but mainly dragons.      ###
###                                                                 ###
#######################################################################

# create a unified kernel image (UKI) via ukify
# by default, the output is written to the current working directory unless specified by the user
create_uki() {
  local microcodes
  local kernel="$1"
  local pkgbase="$2"
  local esp="$3"
  local initrd="/boot/booster.img-${pkgbase}"
  local osrel="/etc/os-release"
  local ukisuffix="uki"
  local efi_output="${esp}/vmlinuz-${pkgbase}-${ukisuffix}.efi"
  #local splash="/usr/share/systemd/bootctl/splash-arch.bmp"

  if [ -f "${efi_output}" ]; then
    echo -e "\033[1;32m===== ${efi_output} already exists =====\033[0m"
  else
  # find all microcodes and delete the trailing white space
  microcodes=$(find /boot -name '*-ucode.img' -type f -printf "/boot/%f " | tr -d ' ')
  microcodes_arg=""
  if [ -n "${microcodes}" ]; then
    microcodes_arg="--initrd=\"$microcodes\""
  fi

  if [ -f "$initrd" ] && [ -n "${DO_NOT_OVERWRITE_EXISTING_INITRD}" ]; then
    echo "Not regenerating initrd for ${pkgbase} at ${initrd}"
  else
    echo "Regenerating initrd for ${pkgbase} at ${initrd}"
    booster build --force --kernel-version "${kernel##/usr/lib/modules/}" "$initrd" \
        || { echo -e "\033[1;33mThere was an issue building the init ramdisk for ${pkgbase}.\033[0m"; }
  fi

  ukify \
      ${microcodes_arg} \
      --initrd="$initrd" \
      --linux="/boot/vmlinuz-${pkgbase}" \
      --os-release="@${osrel}" \
      --output="${efi_output}" \
    build \
        || { echo -e "\033[1;33mThere was an issue generating the UKI for ${pkgbase}.\033[0m"; return; }
  fi
  # Automatically sign ukified EFI archive if sbctl is present.
  if [ $(command -v sbctl) ]; then
    if [[ $($(command -v sbctl) verify --json "${efi_output}" | jq '.[0].is_signed') == 1 ]]; then
      echo -e "\033[1;32m===== ${efi_output} is already signed =====\033[0m"
    else
      $(command -v sbctl) sign -s "${efi_output}" \
          || { echo -e "\033[1;31mThere was an issue signing the UKI for ${pkgbase} located at ${efi_output}.\033[0m"; return; }
      echo -e "\033[1;32m===== ${efi_output} successfully signed =====\033[0m"
    fi
  else
    echo "No sbctl present, will not sign or verify signature."
  fi

  echo -e "\033[1;32m=== ${efi_output} successfully created ===\033[0m"
  echo ""
}

usage() {
  echo "Usage: regenerate_uki build [path]"
  echo "See booster(1) for more info and examples."
}

check_for_package() {
  local target=$1
  local return_instead_of_fail="$2"
  package="$(dpkg-query -l | grep $target || echo '')"
  if [ -z "$package" ]; then
    if [ -n "${return_instead_of_fail}" ]; then
      echo "failure"
    else
      echo -e "\033[1;31m${target} is not installed. Please install ${target} using apt.\033[0m"
      usage
      exit 0
    fi
  else
    if [ -n "${return_instead_of_fail}" ]; then
      echo "$package"
    fi
  fi
}

check_kernel() {
  local target=$1
  local check_kernel=$(check_for_package "$target" true)
  if [ -z "$check_kernel" ] || [ "${check_kernel}" == "failure" ]; then
    echo "0"
  fi
  echo "1"
}

main() {
  local esp
  local package
  esp=$(pwd)

  if ! [ "$1" == "build" ]; then
    usage
    exit 1
  fi

  if [ -n "$2" ]; then
    esp="$2"
  fi

  if ! [ -d "$esp" ]; then
    echo "Path to ESP does not exist or is not a directory: ${esp}"
    usage
    exit 1
  fi

  # check if the required packages are installed.
  check_for_package "systemd-ukify"
  check_for_package "systemd-boot-efi"

  # check for root
  if ! [ "$EUID" -eq 0 ]; then
    echo "regenerate_uki must be run as root."
    exit 1
  fi

  # find out all installed kernels
  mapfile -d '' kernels < <(find /usr/lib/modules -maxdepth 1 -type d ! -name "modules" -print0)

  for kernel in "${kernels[@]}"; do
    echo -e "\033[1;32m=== Processing ${kernel} ===\033[0m"
    pkgbase="$(basename $kernel)"
    if [ "$(check_kernel "${pkgbase}")" == "0" ]; then
      echo "$target is not a kernel installed by the system. Skipping."
      continue
    fi

    create_uki "$kernel" "$pkgbase" "$esp"
  done

  wait
}

main "$@"
